apiVersion: v1
kind: Pod
metadata:
  labels:
    run: node-affinity
  name: node-affinity
  namespace: kube-samples
spec:
  containers:
  - image: nginx:1.21
    imagePullPolicy: IfNotPresent
    name: node-affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: worker
            operator: In
            values:
            - "3"
