apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-affinity
  name: pod-affinity
  namespace: kube-samples
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: run
            operator: In
            values:
            - "node-affinity"
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: nginx:1.21
