apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-autoscaler
  namespace: samples
spec:
  minReplicas: 3      # 最小pod数量
  maxReplicas: 9      # 最大pod数量
  targetCPUUtilizationPercentage: 3      # cpu 使用率指标
  scaleTargetRef:           #指定要控制的信息
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment