# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ha-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.23.5
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
  extraMounts:
  - hostPath: /mnd/d/data/k8s/mount/files
    containerPath: /files
    readOnly: true
- role: control-plane
  image: kindest/node:v1.23.5
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30001
- role: control-plane
  image: kindest/node:v1.23.5
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30002
- role: worker
  image: kindest/node:v1.23.5
- role: worker
  image: kindest/node:v1.23.5
- role: worker
  image: kindest/node:v1.23.5