# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multi-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.23.5
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
- role: worker
  image: kindest/node:v1.23.5
- role: worker
  image: kindest/node:v1.23.5