apiVersion: batch/v1
kind: CronJob
metadata:
  name: echo-cron-job
  namespace: samples
  labels:
    controller: echo-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: echo-cron-c
            image: centos:7.9.2009
            command:    # ["/bin/sh","-c","for i in 5 4 3 2 1;do echo ${i};sleep 3;done"]
            - "/bin/sh"
            - "-c"
            - "for i in `seq 1 10`;do echo ${i};sleep 1;done"