apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  namespace: samples
  labels:
    run: simple-pod
spec:
  containers:
  - name: nginx-c
    image: nginx:1.21
    imagePullPolicy: IfNotPresent
    ports:
    - name: nginx-c-p80
      containerPort: 80   # 容器要监听的端口
      protocol: TCP       # 端口协议，必须是UDP，TCP，或者SCTP。默认TCP
      # hostPort:            # 一般省略，设置会独占宿主机某个端口
      # hostIP:              # 一般省略,要将外部端口绑定到的主机ip
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
  - name: centos-c
    image: centos:7.9.2009
    command: ["/bin/bash","-ce","tail -f /dev/null"]
    env:
    - name: username
      value: admin
    - name: password
      value: "123456"
