apiVersion: apps/v1
kind: Deployment    # 设置类型
metadata:
  name: nginx-deployment
  namespace: samples
spec:
  strategy:
    type: Recreate  # RollingUpdate
  replicas: 9       # 设置副本数量，修改副本数量实现扩缩容
  selector:
    matchLabels:
      run: nginx-pod
  template:         # 设置模板
    metadata:
      labels:
        run: nginx-pod
    spec:
      containers:
      - name: nginx-c
        image: nginx:1.21